version: "3.9"

services:
  db:
    image: postgres:14
    container_name: evoting_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "testdb"]
      interval: 1s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile  # или просто Dockerfile, если вы его переименовали
    container_name: evoting_test_runner
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb
    volumes:
      - .:/app
    ports:
      - "8000:8000"       # Проброс порта для доступа к API извне
    command: >
      bash -c "
        python scripts/setup_db.py &&
        uvicorn election_app.api.main:app --host 0.0.0.0 --port 8000 --reload
      "
