import createClient from 'openapi-fetch';
import type { paths } from './schema'; // generated by openapi-typescript
import { authMiddleware } from './auth-middleware';
import { ref } from 'vue';
import { BASE_URL } from '@/consts';

export const client = createClient<paths>({
    baseUrl: BASE_URL,
});

client.use(authMiddleware);

export const useApi = () => {
    const api = ref(client);
    return api;
};